version: '3.7'
services: 
  nest-api: 
    build: ./  
    volumes: 
      - ./:/usr/src/api
    ports: 
      - 3000:3000 
    command: npm run start:dev 
    networks: 
      - nest-network

    environment:  
      - NODE_ENV=development

networks:  
  nest-network:
    driver: bridge