version: '3.7'
services: 
  nest-api: 
    build: ./  
    volumes: 
      - ./:/usr/src/api
    ports: 
      - 3000:3000 
    networks: 
      - nest-network
    command: npm run start:dev 

    environment:  
      - NODE_ENV=development

  mysql:
    image: mysql:5.7
    networks: 
      - nest-network
    ports: 
    - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydbname
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

networks:  
  nest-network:
    driver: bridge